W5D1/musictest/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:create, :new, :destroy]
  resources :albums, only: [:new, :create, :edit, :destroy, :show]
  resources :tracks, only: [:show, :create, :destroy, :edit, :new]
  resources :bands
end

W5D1/musictest/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band, foreign_key: :band_id
  has_many :tracks, dependent: :destroy
end

W5D1/musictest/app/models/band.rb
class Band < ApplicationRecord
  has_many :albums, foreign_key: :band_id, dependent: :destroy
end

W5D1/musictest/app/models/track.rb
class Track < ApplicationRecord
belongs_to :album
end

W5D1/musictest/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password
  validates :email, :password_digest, :session_token, presence: true

  after_initialize :ensure_token
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end
  def gen_token
    SecureRandom::urlsafe_base64
  end

  def ensure_token
    self.session_token ||= gen_token
  end

  def reset_token!
    self.session_token = gen_token
    self.save!
    self.session_token

  end

  def validate_password(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    u = User.find_by(email: email)
    return nil if u.nil?
    if u.validate_password(password)
      return u
    end
    nil
  end
end

W5D1/musictest/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      render :show
    else
      flash.now[:error] = ["Error saving album"]
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def destroy
  end

  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :live, :band_id)
  end
end

W5D1/musictest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    return nil unless session[:session_token]
    @current_user ||=  User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.session_token
  end

  def logout!
    return nil unless session[:session_token]
    session[:session_token] = nil
  end

  def logged_in?
    # debugger
    return false unless session[:session_token].nil?
    true
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to current_user if logged_in?
  end
end

W5D1/musictest/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to @band
    else
      flash.now[:error] = ["band save failed"]
      render :new
    end
  end

  def new
    render :new
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def update
    @band = Band.find_by(id: params[:id])
    return nil if @band.nil?
    if @band.update(band_params)
      render :show
      return
    else
      flash.now[:errors] = ["band failed to update"]
      render :edit
    end
  end

  def destroy
    band = Band.find_by(id: params[:id])
    if !band.nil?
      band.destroy
    else
      flash.now[:error] = ["no band selected to destroy"]
      render :index
      return
    end
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

end

W5D1/musictest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :require_logged_in, only: [:destroy]
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["bad login"]
      render :new
    else
      login!(user)
      redirect_to user
    end
  end

  #show current user
  def show
    # current_user
    # fail

    redirect_to current_user
  end

  def destroy
    #not getting here
    logout!
    redirect_to new_session_url
  end
end

W5D1/musictest/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)
    # fail
    if @track.save
      render :show
    else
      debugger
      flash.now[:error] = ["wrong track params"]
      render :new
    end
  end

  def new
    render :new
  end

  def edit
  end

  def destroy
  end

  private

  def track_params
    params.require(:track).permit(:title, :ord, :bonus, :album_id)
  end
end

W5D1/musictest/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_logged_in, only: [:show]
  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    return nil if @user.nil?
    if @user.save
      login!(@user)
      redirect_to bands_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W5D1/musictest/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/musictest/app/helpers/application_helper.rb
module ApplicationHelper
  def user_status(user)
    "Logged in as: #{user.email}"
  end
end

W5D1/musictest/app/helpers/bands_helper.rb
module BandsHelper
end

W5D1/musictest/app/helpers/sessions_helper.rb
module SessionsHelper
end

W5D1/musictest/app/helpers/tracks_helper.rb
module TracksHelper
end

W5D1/musictest/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/musictest/app/views/albums/new.html.erb
<h1>make a new album</h1>
<form action="<%= albums_url %>" method="post">
  title:<input type="text" name="album[title]">
  year:<input type="year" name="album[year]">
  Live album?<input type="radio" name="album[live]" value="true">Yes
  <input type="radio" name="album[live]" value="false">No
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"> <%= band.name %></option>
    <% end  %>
  </select>
  <input type="submit" value="SUBMIT">
</form>

W5D1/musictest/app/views/albums/show.html.erb
<h1>show album</h1>
<%= @album.title %>
<%= @album.year %>
<%= @album.band.name %>
<h2>Tracks</h2>
<ol>
<% @album.tracks.order(:ord).each do |track|  %>
  <li><a href="<%= track_url(track) %>"><%= track.title %></a></li>
<% end %>
</ol>

<a href=" <%= new_track_url %>">Add new track</a>

W5D1/musictest/app/views/bands/edit.html.erb
<h1>Edit band</h1>
<form action=" <%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
band name:<input type="text" name="band[name]" value="<%= @band.name %>">
<input type="submit" value="Enter">
</form>

W5D1/musictest/app/views/bands/index.html.erb
Bands index
<ul>
<a href= "<%= new_band_url %>">Make new band</a>
<% Band.all.each do |band| %>
<li><a href=" <%= band_url(band) %>"><%= band.name %></a></li>
<%= button_to "Delete", band, method: :delete %>
<% end %>
</ul>

W5D1/musictest/app/views/bands/new.html.erb
<form action=" <%= bands_url %>" method="post">
band name:<input type="text" name="band[name]">
<input type="submit" value="Enter">
</form>

W5D1/musictest/app/views/bands/show.html.erb
<!-- There should be  quick way to add album for this band -->
<h2><%= @band.name %></h2>
<a href=" <%= edit_band_url %>">Edit band</a>
<br>
<h2>Albums</h2>
<% @band.albums.each do |album| %>
  <a href= "<%= album_url(album) %>"> <%= album.title %> </a> <br>
<% end %>
<h2>Delete?</h2>
<%= button_to "Delete band!", band_url, method: :delete %>

W5D1/musictest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <div class="topnav">
        <h1>Welcome to the simple music app!</h1>
        <a href=" <%= bands_url %>">Bands Index</a>
        <a href=" <%= new_album_url %>">Add new album</a>
        <% if current_user.nil? %>
          <%= button_to "login", new_session_url, method: :get %>
        <% else %>
        <%= user_status(current_user) %>
        <%= button_to "logout", session_url, method: :delete %>
        <% end %>
    </header>
    <%= yield %>
  </body>
</html>

W5D1/musictest/app/views/users/new.html.erb
<h1>New user</h1>
<form action=" <%= users_url %>" method="post">
  email<input type="text" name="user[email]" id="Email">
  password<input type="text" name="user[password]" id="password">
  <label for="Create User">
  <input type="submit" value="Create User" id="Create User">
  </label>
</form>

W5D1/musictest/app/views/users/show.html.erb
<h1>show page</h1>

<form action=" <%= session_url %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Logout">
</form>